apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myteam
spec:
  generators:
    - list:
        elements:
          - cluster: nonprod
            url: https://192.168.1.172:6551
          - cluster: prod
            url: https://192.168.1.172:6552
  template:
    metadata:
      name: "guestbook-{{ cluster }}"
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: "myteam-{{env}}"
      syncPolicy:
        automated: {}
      sources:
        - repoURL: https://github.com/rickdennis/argocd-example-apps.git
          path: helm-guestbook
          helm:
            valueFiles:
              - $values/myteam/values.yaml
              - "$values/myteam/{{ cluster }}/values.yaml"
        - repoURL: https://github.com/rickdennis/argocd-values.git
          ref: values
